### ISSUE TITLE
一个小的关于dictionary的想法

### ISSUE THREAD

**Issue by sNaticY** [zhangqi-ulua/XlsxToLua#2]
齐王殿下，见信好
目前的Excel-Lua的解析工具，在配置技能时，不得不使用param1, param2此类的名称，添加注释如"攻击范围"，再在脚本中自行根据需求使用。看起来是一个很不优雅的过程需要两边对照使用非常麻烦，而且一旦注释没有及时更新很容易出错。
鉴于lua table的灵活的能力，想必是可以实现真正的dictionary的，即

- dictionary首列填写名称dict1，类型(dictionary)，对应的每行填写key-value pair的数量N，或将N标记在类型的后面
- 后续的N*2列中，两列为一组，第一列填写string类型的值作为key，第二列填写value，通常float可以满足需求。
- 再后续的列正常填写即可

假设下表为LogicDataSkill的一部分

|技能id|技能参数    |            |         |            |        |耗蓝|
|--|----|---------|-------|----|-----|-----|
|id|skillParams |           |          |            |        |cost|
|int|dictionary:[2]   |string |float |string     |float|int|
|101|                  |range |5.2   |damage |170  |150|
|102|                  |speed|0.8   |distance |350  |220|
|103|                 |cooldown |15   |enemyNum |4  |1130|

在lua中使用时，即可直接调用

``` lua
local skillId = 101
local skillData = logicDataSkill[skillId]
local demage = skillData.skillParams.damage
```

这样就不依赖param1,param2的顺序和注释，可任意调整次序，调整参数数量，策划填写和程序使用都会非常方便。

不知以上方案是否可行，还请齐王殿下不吝赐教

**Comment by zhangqi-ulua** [comment]
刘严，这个我是不赞同的，这样确实灵活了。但是更容易出错了（属性名每次都要填在单元格里了，万一拼写错了呢？），而且策划在配置时，即便你提供这样的功能，为了整洁和易于管理，大家也会把同属性的放到一列中，哪怕有一个技能并不涉及，就把这一单元格数据留空。对于Excel，可以使用列筛选功能很方便的去筛选管理同属性列信息。另外，param1这样命名肯定是不建议的，应该以真实的属性名

以上是我的想法，还请指点

**Comment by sNaticY** [comment]
是这样的，通常不同技能之间，有很多含义完全不同的参数晕眩时间、攻击范围，伤害递减之类的，而且绝大多数的技能都只用到其中的3-4种，所以才被迫使用param1,param2此类的列。否则可能需要空出20+列来把所有类型的各种参数都起好名字，这样整张表格就会非常稀疏。LME的Skill表就可以很好的体现这一点。

**Comment by zhangqi-ulua** [comment]
如果非要这样做的话，我工具中倒有json类型，可以将仅用到的几个属性拼成json串填在一个json格式的单元格中

**Comment by sNaticY** [comment]
嗯，的确是一个可行的解决方案，而且解决了嵌套复杂结构的问题，齐王殿下英明！

但是，BUT，でも。。

Json格式对于策划来说，确实太复杂了。无论是数据筛选和修改的难度，还是表格直观程度，都远不如Dictionary。手写Json串更容易出错，但如果还需要借助其他工具来填写表格内容无疑又增加了新的工作量，我猜，策划在使用的过程中也会尽可能通过拆表等手段避免使用Json结构吧（不负责任的随便猜的，如果猜错了请见谅）。

综上所述，Dictionary的确存在可能的填错的问题，但是其解决的问题价值是大于它带来的风险的。

**Comment by zhangqi-ulua** [comment]
json当然不是手写的啦。。。可以做个专门生成技能表格json的小工具。之前我加入json格式，也是因为有公司的人，他们用工具生成json然后填在表格中，需要我工具支持json转为lua table
