### ISSUE TITLE
已添加-exportKeepDirectoryStructure 能否忽略原表格重名呢

### ISSUE THREAD

**Issue by cnwillz** [zhangqi-ulua/XlsxToLua#6]
添加-exportKeepDirectoryStructure参数本意便是为了方便进行表格分类,已经能够避免了重名

我理解只添加-exportIncludeSubfolder的情况会出现重名冲突

-exportIncludeSubfolder 和 -exportKeepDirectoryStructure 一起出现的情况是否可以忽略重复呢

**Comment by zhangqi-ulua** [comment]
这个我觉得还是按项目实际自己修改代码吧。我觉得直接报错提醒是合理的。

**Comment by cnwillz** [comment]
好的 还是感谢大佬了!
